### ISSUE TITLE
Scenario Not Created When Click "Create a Scenario"

### ISSUE THREAD

**Issue by hsi5484** [samszo/Omeka-S-theme-GenStory#3]
I went to create a scenario but there wasn't anything labeled "scenario" that was created. The items in the story all turned into TrackActions, but again no "scenario" appears in the back half of Omeka or on the Workshop website.

**Comment by samszo** [comment]
There were two issues when creating the scenarios:
1. the rights given to users were not sufficient
2. Scenario creation was too resource-intensive when the story has a lot of elements
The solutions :
1. users are now "supervisors"
2.1 the link between tracks and scenario is made a posteriori in each track
2.2 sources and taget are no longer stored in the scenario item
2.3 the json is no longer stored in a scenario field but in an associated file
