### ISSUE TITLE
Scenario edits not saving 

### ISSUE THREAD

**Issue by lxsgla** [samszo/Omeka-S-theme-GenStory#4]
Hi Samuel,
Haley and I are finding that her scenario A Dream: Roller Coaster can be edited from the timeline, but when we reload and return, it isn't saving. Haley is hitting the "modifier" button from the second edit screen after entering timeline info. Thanks!

**Comment by samszo** [comment]
The problem is solved.
The raison was : the relation hasScenario was not recorded
